import type { NextPage } from "next";
import Head from "next/head";
import { styled } from "../styles";

const Button = styled("button", {
  backgroundColor: "$green300",
  borderRadius: "9999px",
  fontSize: "13px",
  padding: "10px 15px",
  border: 0,
  color: "$white",
  "&:hover": {
    backgroundColor: "$green500",
    cursor: "pointer",
  },
});

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button>Button</Button>
    </div>
  );
};

export default Home;
