import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { HomeContainer, HomeProduct } from "../styles/pages/home";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeContainer>
        <HomeProduct>
          <Image src="/images/camisa1.png" width={520} height={480} alt="" />

          <footer>
            <strong>Camiseta X</strong>
            <span>99.90</span>
          </footer>
        </HomeProduct>

        <HomeProduct>
          <Image src="/images/camisa1.png" width={520} height={480} alt="" />

          <footer>
            <strong>Camiseta X</strong>
            <span>99.90</span>
          </footer>
        </HomeProduct>
      </HomeContainer>
    </>
  );
};

export default Home;
