import axios from "axios";
import { GetServerSideProps, NextPage } from "next";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import { ImageContainer, SuccessContainer } from "../styles/pages/success";
import Image from "next/image";
import Head from "next/head";

type SuccessProps = {
  sessionID: string;
  emptyBag: () => void;
};

type SuccessData = {
  costumerName: string;
  products: {
    image: string;
    productName: string;
  }[];
  quantity: number;
};

const Success: NextPage<SuccessProps> = ({ sessionID, emptyBag }) => {
  const [successData, setSuccessData] = useState({} as SuccessData);

  const fetchSession = async (): Promise<void> => {
    try {
      const response = await axios.get("/api/success", {
        params: {
          sessionID,
        },
      });
      setSuccessData(response.data);
    } catch (error) {
      console.log(error, "Error");
    }
  };

  useEffect(() => {
    fetchSession();
    emptyBag();
  }, []);

  return (
    <>
      <Head>
        <title>Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SuccessContainer>
        <div
          style={{
            display: "flex",
            position: "relative",
            width: "100%",
            justifyContent: "center",
            height: 145,
          }}
        >
          {successData.products?.map((item) => {
            return (
              <ImageContainer
                key={item.image}
                style={
                  successData.products?.length > 1 ? { marginRight: -50 } : {}
                }
              >
                <Image
                  src={item.image}
                  alt={item.productName}
                  width={120}
                  height={110}
                />
              </ImageContainer>
            );
          })}
        </div>

        <h1>Success!</h1>

        <p>
          Uhuu! <strong>{successData?.costumerName}</strong>, your{" "}
          <strong>{successData.quantity} T-shirts</strong> are going to be in
          your home soon!
        </p>

        <Link href="/">Buy more</Link>
      </SuccessContainer>
    </>
  );
};

export default Success;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  if (!query.session_id) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  const sessionID = query.session_id as string;

  return {
    props: {
      sessionID,
    },
  };
};
